# Generated by Django 4.1.13 on 2024-06-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_payment_plan_delete_membershippackage_payment_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='start_date',
            field=models.DateField(default='2024-06-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(help_text='Duration in months'),
        ),
    ]
